### ISSUE TITLE
Allow single KT to run and not automatically destroy resources

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/kafka-tutorials#453]
An iteration of the harness runner for a single KT destroys its resources at the end of its run.  This totally makes sense that it would work this way to validate the KT.

However, this impacts the workflow for the user who wants to run the KT and leave it running to interrogate the system.  This would be a blocker for someone who wants to leave it running and do other steps, query it, etc.

The cleanup happens in the last step of all harnesses, e.g., https://github.com/confluentinc/kafka-tutorials/blob/master/_data/harnesses/filtering/ksql.yml#L106

Harness-runner can take a 3rd parameter, the stages to run. By default it's dev, test, prod.  https://github.com/confluentinc/kafka-tutorials/blob/master/_includes/tutorials/filtering/ksql/code/Makefile#L12

If we switched line 22 to below, it could work:

```
harness-runner ../../../../../_data/harnesses/filtering/ksql.yml $(TEMP_DIR) dev,test
```

This is where the envs get selected. https://github.com/confluentinc/kafka-tutorials/blob/master/harness_runner/harness_runner.py#L134

**Comment by ybyzek** [comment]
@MichaelDrogalis thanks for pointing me in the right direction in terms of identifying the key pieces of code to look at.  

Now to arrive at fix.

The following change appears to work for one KT:

```
diff --git a/_includes/tutorials/filtering/kstreams/code/Makefile b/_includes/tutorials/filtering/kstreams/code/Makefile
index d9255885..b4b52d3b 100644
--- a/_includes/tutorials/filtering/kstreams/code/Makefile
+++ b/_includes/tutorials/filtering/kstreams/code/Makefile
@@ -1,9 +1,10 @@
 STEPS_DIR := tutorial-steps
 DEV_OUTPUTS_DIR := $(STEPS_DIR)/dev/outputs
 TEMP_DIR := $(shell mktemp -d)
+SEQUENCE := "dev, test, prod"
 
 tutorial:
        rm -r $(DEV_OUTPUTS_DIR) || true
        mkdir $(DEV_OUTPUTS_DIR)
-   harness-runner ../../../../../_data/harnesses/filtering/kstreams.yml $(TEMP_DIR)
+ harness-runner ../../../../../_data/harnesses/filtering/kstreams.yml $(TEMP_DIR) $(SEQUENCE)
        diff --strip-trailing-cr $(STEPS_DIR)/dev/expected-output-events.json $(DEV_OUTPUTS_DIR)/actual-output-events.json
```

This allows `make` to be run as the following (note omission of `prod`)

```
make SEQUENCE="dev, test"
```

This approach requires an update to all 44 Makefiles in KT.

Thoughts about this approach?  cc: @MichaelDrogalis @bbejeck

**Comment by ybyzek** [comment]
Note to self:

This GH issue to make the required changes to the KT, as well as update the README to explain how to do this.

**Comment by rspurgeon** [comment]
I vote for Option 1 above.  If a second Makefile target is desired, it could be added but it just delegates to the `tutorial` target passing in the `SEQUENCE` parameter as needed.  That would eliminate the duplication across two targets

**Comment by ybyzek** [comment]
Example of what users can do by running just with `dev, test`:

```
[14:03:38] ~/git/kafka-tutorials/_includes/tutorials/filtering/ksql/code(master) ✗: docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED              STATUS              PORTS                                        NAMES
f7f2cb870068        confluentinc/ksqldb-cli:0.9.0            "/bin/sh"                About a minute ago   Up About a minute                                                ksqldb-cli
9458c2774292        confluentinc/ksqldb-server:0.9.0         "/usr/bin/docker/run"    About a minute ago   Up About a minute   0.0.0.0:8088->8088/tcp                       ksqldb-server
93f125166705        confluentinc/cp-schema-registry:5.5.0    "/etc/confluent/dock…"   About a minute ago   Up About a minute   0.0.0.0:8081->8081/tcp                       schema-registry
b04cda95ec70        confluentinc/cp-enterprise-kafka:5.5.0   "/etc/confluent/dock…"   About a minute ago   Up About a minute   9092/tcp, 0.0.0.0:29092->29092/tcp           broker
02b9c95a65be        confluentinc/cp-zookeeper:5.5.0          "/etc/confluent/dock…"   About a minute ago   Up About a minute   2888/tcp, 0.0.0.0:2181->2181/tcp, 3888/tcp   zookeeper
[14:03:40] ~/git/kafka-tutorials/_includes/tutorials/filtering/ksql/code(master) ✗: docker exec -it broker bash
root@broker:/# ls
bin  boot  dev	etc  home  lib	lib64  media  mnt  opt	proc  root  run  sbin  srv  sys  tmp  usr  var
root@broker:/# kafka-topics --list 
Exception in thread "main" java.lang.IllegalArgumentException: Only one of --bootstrap-server or --zookeeper must be specified
	at kafka.admin.TopicCommand$TopicCommandOptions.checkArgs(TopicCommand.scala:702)
	at kafka.admin.TopicCommand$.main(TopicCommand.scala:52)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)
root@broker:/# kafka-topics --list --bootstrap-server localhost:9092
__confluent.support.metrics
__consumer_offsets
__transaction_state
_confluent-ksql-default__command_topic
_confluent-metrics
_schemas
george_martin_books
publication_events
root@broker:/# exit
exit
[14:04:58] ~/git/kafka-tutorials/_includes/tutorials/filtering/ksql/code(master) ✗: docker exec -it broker bash
root@broker:/# exit
exit
[14:05:03] ~/git/kafka-tutorials/_includes/tutorials/filtering/ksql/code(master) ✗: dock
[14:05:05] ~/git/kafka-tutorials/_includes/tutorials/filtering/ksql/code(master) ✗: docker exec broker kafka-topics --list --bootstrap-server localhost:9092
__confluent.support.metrics
__consumer_offsets
__transaction_state
_confluent-ksql-default__command_topic
_confluent-metrics
_schemas
george_martin_books
publication_events
[14:05:15] ~/git/kafka-tutorials/_includes/tutorials/filtering/ksql/code(master) ✗: docker exec -it ksqldb-cli ksql http://ksqldb-server:8088               
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
                  
                  ===========================================
                  =       _              _ ____  ____       =
                  =      | | _____  __ _| |  _ \| __ )      =
                  =      | |/ / __|/ _` | | | | |  _ \      =
                  =      |   <\__ \ (_| | | |_| | |_) |     =
                  =      |_|\_\___/\__, |_|____/|____/      =
                  =                   |_|                   =
                  =  Event Streaming Database purpose-built =
                  =        for stream processing apps       =
                  ===========================================

Copyright 2017-2020 Confluent Inc.

CLI v0.9.0, Server v0.9.0 located at http://ksqldb-server:8088

Having trouble? Type 'help' (case-insensitive) for a rundown of how things work!

ksql> show streams;

 Stream Name      | Kafka Topic         | Format 
-------------------------------------------------
 ALL_PUBLICATIONS | publication_events  | AVRO   
 GEORGE_MARTIN    | george_martin_books | AVRO   
-------------------------------------------------
ksql> exit
Exiting ksqlDB.
```

**Comment by ybyzek** [comment]
cc: @vdesabou I think this change would benefit a workflow you are interested in as well.

**Comment by ybyzek** [comment]
Addressed via https://github.com/confluentinc/kafka-tutorials/pull/454
